<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\VocabularyTopic;
use App\Models\VocabularyCategory;
use App\Models\Vocabulary;

class VocabularyN400Seeder extends Seeder
{
    public function run(): void
    {
        $topic = VocabularyTopic::firstOrCreate([
            'name' => 'Từ vựng N-400',
            'slug' => 'n400'
        ]);

        $category = VocabularyCategory::firstOrCreate([
            'topic_id' => $topic->id,
            'name' => 'Thông tin cá nhân',
            'slug' => 'personal-info'
        ]);

        $vocabularies = [
            [
                'word' => 'Attending school',
                'meaning' => 'đi học',
                'hint' => null,
                'example' => null,
            ],
            [
                'word' => 'Birthday/date of birth',
                'meaning' => 'ngày sinh',
                'hint' => null,
                'example' => null,
            ],
            [
                'word' => 'Child/children',
                'meaning' => 'con, trẻ em',
                'hint' => null,
                'example' => null,
            ],
            [
                'word' => 'Company/workplace',
                'meaning' => 'công ty',
                'hint' => null,
                'example' => null,
            ],
            [
                'word' => 'Currently/current',
                'meaning' => 'hiện tại',
                'hint' => null,
                'example' => null,
            ],
            [
                'word' => 'Disability',
                'meaning' => 'khuyết tật',
                'hint' => null,
                'example' => null,
            ],
            [
                'word' => 'Employ/employed',
                'meaning' => 'đi làm',
                'hint' => null,
                'example' => null,
            ],
            [
                'word' => 'Full name',
                'meaning' => 'tên đầy đủ',
                'hint' => null,
                'example' => null,
            ],
            [
                'word' => 'Hispanic',
                'meaning' => 'người gốc Tây Ban Nha',
                'hint' => null,
                'example' => null,
            ],
            [
                'word' => 'Latino',
                'meaning' => 'người gốc Mỹ Latin',
                'hint' => null,
                'example' => null,
            ],
            [
                'word' => 'Marital status',
                'meaning' => 'tình trạng hôn nhân',
                'hint' => null,
                'example' => null,
            ],
            [
                'word' => 'Mental impairment',
                'meaning' => 'suy giảm trí tuệ',
                'hint' => null,
                'example' => null,
            ],
            [
                'word' => 'Nationality',
                'meaning' => 'quốc tịch',
                'hint' => null,
                'example' => null,
            ],
            [
                'word' => 'Social Security Number',
                'meaning' => 'số An sinh Xã hội',
                'hint' => null,
                'example' => null,
            ],
            [
                'word' => 'Spouse',
                'meaning' => 'vợ/chồng',
                'hint' => null,
                'example' => null,
            ],
            [
                'word' => 'Trips abroad',
                'meaning' => 'chuyến đi nước ngoài',
                'hint' => null,
                'example' => null,
            ],
            [
                'word' => 'U.S. citizen',
                'meaning' => 'công dân Mỹ',
                'hint' => null,
                'example' => null,
            ],
        ];

        foreach ($vocabularies as $vocab) {
            Vocabulary::create([
                'category_id' => $category->id,
                'word' => $vocab['word'],
                'meaning' => $vocab['meaning'],
                'hint' => $vocab['hint'],
                'example' => $vocab['example'],
            ]);
        }

        $category = VocabularyCategory::firstOrCreate([
            'topic_id' => $topic->id,
            'name' => 'Định nghĩa',
            'slug' => 'define'
        ]);

        $vocabularies = [
            [
                'word' => 'Claim',
                'meaning' => 'Thừa nhận',
                'synonymous' => 'To say something is true',
                'synonymous_translate' => 'Nói điều gì đó là đúng',
                'hint' => 'tu say sâm-thing i-(s) tru',
                'example' => null,
            ],
            [
                'word' => 'Claim to be a U.S. citizen',
                'meaning' => 'Tự khai mình là công dân Mỹ',
                'synonymous' => 'To state you are a U.S. citizen',
                'synonymous_translate' => 'Tự khai mình là công dân Mỹ',
                'hint' => null,
                'example' => null,
            ],
            [
                'word' => 'Vote',
                'meaning' => 'Bỏ phiếu',
                'synonymous' => 'To choose new leaders.',
                'synonymous_translate' => 'Chọn ra lãnh đạo mới',
                'hint' => 'tu chu-(s) niu li-dờ-(s)',
                'example' => null,
            ],
            [
                'word' => 'Owe',
                'meaning' => 'Nợ',
                'synonymous' => 'To not pay yet.',
                'synonymous_translate' => 'Là chưa trả',
                'hint' => 'tu nót pay dét-(t)',
                'example' => null,
            ],
            [
                'word' => 'Owe taxes',
                'meaning' => 'Nợ thuế',
                'synonymous' => 'To not pay money to the government yet',
                'synonymous_translate' => 'Là chưa trả tiền cho chính phủ.',
                'hint' => null,
                'example' => null,
            ],
            [
                'word' => 'Overdue',
                'meaning' => 'Quá hạn',
                'synonymous' => 'To past a deadline',
                'synonymous_translate' => 'Là đã trễ so với thời hạn được yêu cầu',
                'hint' => 'to pát-s-(t) ờ đét-lai',
                'example' => null,
            ],
            [
                'word' => 'File a tax return',
                'meaning' => 'Khai thuế',
                'synonymous' => 'To send tax paperwork to the government.',
                'synonymous_translate' => null,
                'hint' => 'tu sen-(d) tát-(s) pay-pờ-quớt-(k) tu đờ gó-vơ-mần-(t)',
                'example' => null,
            ],
            [
                'word' => 'Communist Party',
                'meaning' => 'Đảng cộng sản',
                'synonymous' => null,
                'synonymous_translate' => 'Là giống như Trung Quốc, Triều Tiên',
                'hint' => 'lai-(k) chai-nờ, no-th cờ-ri-à',
                'example' => null,
            ],
            [
                'word' => 'Totalitarian',
                'meaning' => 'Toàn trị',
                'synonymous' => null,
                'synonymous_translate' => 'Chính phủ kiểm soát mọi thứ và người dân không có quyền lực.',
                'hint' => 'đờ gó-vơ-mần-(t) cần-trô-(s) e-v-ri-thinh èn pi-pồ ha-(v) nâu pao-quờ',
                'example' => null,
            ],
            [
                'word' => 'Overthrow',
                'meaning' => 'Lật đổ chính phủ',
                'synonymous' => 'To remove a government from power',
                'synonymous_translate' => 'Là làm cho một chính phủ mất quyền lực',
                'hint' => 'tu ri-mu-(v) a gó-vơ-mần-(t) ph-rom pao-quờ',
                'example' => null,
            ],
            [
                'word' => 'Assault',
                'meaning' => 'Làm hại người khác',
                'synonymous' => 'To hurt someone',
                'synonymous_translate' => 'Làm hại người khác',
                'hint' => null,
                'example' => null,
            ],
            [
                'word' => 'Sabotage',
                'meaning' => 'Cố ý phá hoại',
                'synonymous' => 'To destroy something on purpose.',
                'synonymous_translate' => 'Cố tình phá hoại thứ gì đó',
                'hint' => null,
                'example' => null,
            ],
            [
                'word' => 'Weapon',
                'meaning' => 'Vũ khí',
                'synonymous' => null,
                'synonymous_translate' => 'Như dao hoặc súng',
                'hint' => null,
                'example' => null,
            ],
            [
                'word' => 'Explosive',
                'meaning' => 'Like bomb or TNT',
                'synonymous' => null,
                'synonymous_translate' => 'Như bom hoặc TNT',
                'hint' => 'lai-(k) bom-(b) o ti-en-ti',
                'example' => null,
            ],
            [
                'word' => 'Kidnapping',
                'meaning' => 'Bắt cóc',
                'synonymous' => 'To take someone away by force.',
                'synonymous_translate' => 'Bắt ai đó bằng vũ lực',
                'hint' => null,
                'example' => null,
            ],
            [
                'word' => 'Assassination',
                'meaning' => 'Ám sát',
                'synonymous' => 'To kill someone important, like a president or a leader.',
                'synonymous_translate' => 'Giết một người quan trọng, như Tổng thống hoặc một vị lãnh đạo.',
                'hint' => null,
                'example' => null,
            ],
            [
                'word' => 'Hijacking',
                'meaning' => 'Cướp phương tiện',
                'synonymous' => 'To take control of a vehicle by force',
                'synonymous_translate' => 'Chiếm quyền điều khiển phương tiện bằng vũ lực',
                'hint' => null,
                'example' => null,
            ],
            [
                'word' => 'Torture',
                'meaning' => 'Tra tấn',
                'synonymous' => 'To hurt someone',
                'synonymous_translate' => 'Là làm đau người khác',
                'hint' => null,
                'example' => null,
            ],
            [
                'word' => 'Genocide',
                'meaning' => 'Diệt chủng',
                'synonymous' => 'To kill a whole race',
                'synonymous_translate' => 'Là giết cả chủng tộc',
                'hint' => null,
                'example' => null,
            ],
            [
                'word' => 'Military unit',
                'meaning' => 'Đơn vị quân đội',
                'synonymous' => 'A group of soldiers',
                'synonymous_translate' => 'Một nhóm quân lính',
                'hint' => null,
                'example' => null,
            ],
            [
                'word' => 'Paramilitary unit',
                'meaning' => 'Đơn vị bán quân sự',
                'synonymous' => null,
                'synonymous_translate' => 'Là quân đội không chính thức',
                'hint' => null,
                'example' => null,
            ],
            [
                'word' => 'Prison or jail',
                'meaning' => 'Trại giam, nhà tù',
                'synonymous' => 'A place where prisoners are kept.',
                'synonymous_translate' => 'Nơi phạm nhân bị giữ lại.',
                'hint' => null,
                'example' => null,
            ],
            [
                'word' => 'Detained',
                'meaning' => 'Bị giam giữ',
                'synonymous' => null,
                'synonymous_translate' => 'Bị cảnh sát giữ lại ở một nơi',
                'hint' => null,
                'example' => null,
            ],
            [
                'word' => 'Weapon training',
                'meaning' => 'Huấn luyện sử dụng vũ khí',
                'synonymous' => 'To learn how to use guns',
                'synonymous_translate' => 'Là học cách sử dụng súng',
                'hint' => null,
                'example' => null,
            ],
            [
                'word' => 'Military-type training',
                'meaning' => 'Huấn luyện kiểu quân sự',
                'synonymous' => 'To train like soldiers',
                'synonymous_translate' => 'Là huấn luyện như quân lính',
                'hint' => null,
                'example' => null,
            ],
            [
                'word' => 'Armed group',
                'meaning' => 'Nhóm vũ trang',
                'synonymous' => 'A group of people with weapons',
                'synonymous_translate' => 'Một nhóm người trang bị vũ khí.',
                'hint' => null,
                'example' => null,
            ],
            [
                'word' => 'Combat',
                'meaning' => 'Chiến đấu',
                'synonymous' => 'To fight in a war',
                'synonymous_translate' => 'Đánh nhau trong chiến tranh',
                'hint' => null,
                'example' => null,
            ],
            [
                'word' => 'Crime',
                'meaning' => 'Tội phạm',
                'synonymous' => null,
                'synonymous_translate' => 'Hành động vi phạm pháp luật',
                'hint' => 'đì ác-sần đát-(t) b-rây-(k) đờ lo',
                'example' => null,
            ],
            [
                'word' => 'Commit a crime',
                'meaning' => 'Phạm tội',
                'synonymous' => 'To do something that breaks the law',
                'synonymous_translate' => 'Làm điều gì đó trái pháp luật',
                'hint' => null,
                'example' => null,
            ],
            [
                'word' => 'Arrested',
                'meaning' => 'Bị bắt',
                'synonymous' => null,
                'synonymous_translate' => 'Bị cảnh sát giam giữ',
                'hint' => null,
                'example' => null,
            ],
            [
                'word' => 'Offense',
                'meaning' => 'Phàm tội nhẹ',
                'synonymous' => 'A minor crime:',
                'synonymous_translate' => 'Một tội nhẹ',
                'hint' => 'Phát âm dễ nhớ',
                'example' => null,
            ],
            [
                'word' => 'Cited',
                'meaning' => 'Bị vé phạt',
                'synonymous' => null,
                'synonymous_translate' => 'Bị cảnh sát ghi giấy phạt',
                'hint' => null,
                'example' => null,
            ],
            [
                'word' => 'Confined',
                'meaning' => 'Bị giam giữ/bị giới hạn trong một khu vực',
                'synonymous' => null,
                'synonymous_translate' => 'Bị giữ lại ở một nơi',
                'hint' => null,
                'example' => null,
            ],
            [
                'word' => 'Prostitute',
                'meaning' => 'Người bán dâm',
                'synonymous' => 'A person who has sex for money.',
                'synonymous_translate' => 'Người làm tình để lấy tiền',
                'hint' => null,
                'example' => null,
            ],
            [
                'word' => 'Procure',
                'meaning' => 'Môi giới',
                'synonymous' => 'To find a prostitute for someone',
                'synonymous_translate' => 'Tìm người bán dâm cho ai đó',
                'hint' => null,
                'example' => null,
            ],
            [
                'word' => 'Illegal drug, narcotics',
                'meaning' => 'Chất cấm, ma túy',
                'synonymous' => null,
                'synonymous_translate' => 'Như heroin',
                'hint' => null,
                'example' => null,
            ],
            [
                'word' => 'Drug paraphernalia',
                'meaning' => 'Đồ dùng ma túy',
                'synonymous' => null,
                'synonymous_translate' => '“Đồ dùng ma túy” là gì?',
                'hint' => null,
                'example' => null,
            ],
            [
                'word' => 'Immigration benefit',
                'meaning' => 'Quyền lợi di trú',
                'synonymous' => null,
                'synonymous_translate' => null,
                'hint' => 'Phát âm dễ nhớ',
                'example' => null,
            ],
            [
                'word' => 'Gamble',
                'meaning' => 'Đánh bạc',
                'synonymous' => 'To play games for money',
                'synonymous_translate' => 'Là chơi trò chơi để kiếm tiền',
                'hint' => null,
                'example' => null,
            ],
            [
                'word' => 'Pay alimony',
                'meaning' => 'Trả tiền cấp dưỡng',
                'synonymous' => 'To give money to ex-spouse after divorce',
                'synonymous_translate' => 'Là trả tiền cấp dưỡng cho vợ/chồng cũ sau ly hôn',
                'hint' => null,
                'example' => null,
            ],
            [
                'word' => 'Public benefit',
                'meaning' => 'Phúc lợi công cộng',
                'synonymous' => null,
                'synonymous_translate' => 'Chính phủ giúp đỡ như tiền, phiếu ăn',
                'hint' => null,
                'example' => null,
            ],
            [
                'word' => 'False',
                'meaning' => 'Sai',
                'synonymous' => null,
                'synonymous_translate' => 'Không đúng',
                'hint' => null,
                'example' => null,
            ],
            [
                'word' => 'Fraudulent',
                'meaning' => 'Nói dối',
                'synonymous' => 'To lie',
                'synonymous_translate' => 'tu lai',
                'hint' => null,
                'example' => null,
            ],
            [
                'word' => 'Deportation proceedings',
                'meaning' => 'Thủ tục trục xuất',
                'synonymous' => null,
                'synonymous_translate' => 'Quy trình đưa một người ra khỏi Mỹ',
                'hint' => null,
                'example' => null,
            ],
            [
                'word' => 'Drafted',
                'meaning' => 'Gọi nhập ngũ',
                'synonymous' => null,
                'synonymous_translate' => 'Được chọn vào quân đội',
                'hint' => null,
                'example' => null,
            ],
            [
                'word' => 'Hereditary title',
                'meaning' => 'Tước vị thừa kế',
                'synonymous' => 'A royal title, like prince or princess',
                'synonymous_translate' => null,
                'hint' => null,
                'example' => null,
            ],
            [
                'word' => 'Oath of Allegiance',
                'meaning' => 'Lời Tuyên thệ Trung thành',
                'synonymous' => 'A promise to be loyal to the United states',
                'synonymous_translate' => 'Lời hứa trung thành với Mỹ',
                'hint' => null,
                'example' => null,
            ],
            [
                'word' => 'Bear arm',
                'meaning' => 'Cầm vũ khí',
                'synonymous' => 'To own or use a gun',
                'synonymous_translate' => 'Như sở hữu và sử dụng súng',
                'hint' => 'Phát âm dễ nhớ',
                'example' => null,
            ],
            [
                'word' => 'Noncombatant service',
                'meaning' => 'Nhiệm vụ không chiến đấu',
                'synonymous' => null,
                'synonymous_translate' => 'Hỗ trợ quân đội, nhưng không chiến đấu trực tiếp',
                'hint' => 'Phát âm dễ nhớ',
                'example' => null,
            ],
        ];

        foreach ($vocabularies as $vocab) {
            Vocabulary::create([
                'category_id' => $category->id,
                'word' => $vocab['word'],
                'meaning' => $vocab['meaning'],
                'synonymous' => $vocab['synonymous'],
                'synonymous_translate' => $vocab['synonymous_translate'],
                'hint' => $vocab['hint'],
                'example' => $vocab['example'],
            ]);
        }
    }
}
